service: FilmsLocationService

provider:
  name: aws
  runtime: python3.7
  stage: prod
  region: sa-east-1

functions:
  films-location:
    handler: handler.handler
    events:
      - http: 
          path: /films
          method: get
          cors: true

plugins:
  - serverless-python-requirements
  - serverless-offline
