version: 2

build-cache: &build-cache
  key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

install-requirements: &install-requirements
  command: |
    python3 -m venv venv
    . venv/bin/activate
    pip install -r requirements.txt

run-tests: &run-tests
  command: |
    . venv/bin/activate
    python -m unittest

build: &build
  docker:
    - image: circleci/python:3.6
  steps:
    - checkout
    - restore_cache:
        <<: *build-cache
    - run:
        name: Installing dependencies
        <<: *install-requirements
    - save_cache:
        <<: *build-cache
        paths:
          - "venv"
    - run:
        name: Running tests
        <<: *run-tests
jobs:
  build:
    <<: *build